### ISSUE TITLE
All the links to jars on the update site https://ecd-plugin.github.io/update/ result in 404 file not found error

### ISSUE THREAD

**Issue by nikopp** [ecd-plugin/ecd#102]
Hi,

I tried to install Enhanced Class Decompiler 3.4.0 via Eclipse Marketplace in Eclipse 2023-06.

The following error occurred:

> An error occurred while collecting items to be installed session context was:(profile=epp.package.java, phase=org.eclipse.equinox.internal.p2.engine.phases.Collect, operand=, action=).
> No repository found containing: osgi.bundle,org.sf.feeling.decompiler,3.3.0
> No repository found containing: org.eclipse.update.feature,org.sf.feeling.decompiler,3.3.0

I tried to find the reason and noticed, that all links to jar files (e.g. https://ecd-plugin.github.io/update/features/org.sf.feeling.decompiler_3.3.0.jar) on https://ecd-plugin.github.io/update result in a 404 error.

Is that the reason for the failed install?

Thanks!

**Comment by jpstotz** [comment]
ECD 3.4.0 should only reference bundles of the same version. I am not sure why your Eclipse version is trying to download files from ECD 3.3.0. I have to check where the 3.3.0 references come from.

**Comment by nikopp** [comment]
Hi Jan,

Thank you for the immediate reply.

So it's normal, that the links on the update site don't work?

I thought that it might be looking for version 3.3 because I don't use the
newest Eclipse version.

Niko

Jan S. ***@***.***> schrieb am Mo., 15. Jan. 2024, 14:53:

**Comment by nikopp** [comment]
Hi Jan,

I guess the references come from https://github.com/ecd-plugin/update/blob/master/category.xml.

Niko

**Comment by nikopp** [comment]
Thanks for the fix, @jpstotz!

I can confirm that the marketplace install works for me now.
