### ISSUE TITLE
Cannot debug with Eclipse 2024-03

### ISSUE THREAD

**Issue by khorser** [ecd-plugin/ecd#107]
Eclipse version 2023-12 and earlier allowed to set breakpoints and debug decompiled code (JD-Core/Fernflower but also CFR worked in most circumstances).
But with 2024-03 I cannot set breakpoints with either decompiler. Am I missing any obscure settings?

**Comment by jpstotz** [comment]
Sorry but I can not reproduce that (tested with JD-core). Debugging a JAR file works fine in my Eclipse 2024-03 installation. 

May be some relics of older ECD installations are still installed? I would recommend to uninstall all ECD features and plugins, restart Eclipse and reinstall ECD v3.5.

**Comment by khorser** [comment]
Thanks @jpstotz
A fresh Eclipse installation did not help but breakpoints started working with JD-Core and Procyon once I removed most JARs from the Classpath (there used to be 600+ files but only a handful were needed for my purposes). Probably Eclipse did not like some of them.
