### ISSUE TITLE
Install failed with Eclipse Oxygen

### ISSUE THREAD

**Issue by jc7447** [ecd-plugin/ecd#11]
Hello,

I tried to install the plugin in Eclipse Oxygen but I got this error : 

`Unable to read repository at https://ecd-plugin.github.io/update/content.xml`

I tried the drag'n'drop method and  the"Install New Software..." method. I also tried directly from the marketplace.

It seems that Eclipse wants a "content.xml" file to proceed.

**Comment by RobertZenz** [comment]
Interesting, but I'm unable to reproduce this on my Mars installation. The error metrics on the Marketplace site also do not indicate that this is a wide spread problem and I have installed it on several Oxygen installations without a problem.

Also, the content.xml is contained inside the content.jar, which is present.

Odd...can I ask you to restart Eclipse and try again? Is there anything special about your setup, like a proxy or similar? Do you have anything "special" installed in your Eclipse environment? Can I ask you to try it with a new Oxygen installation?

**Comment by jc7447** [comment]
Indeed, I have tried with a fresh install of Oxygen on another workstation and it works fine.

I was behind a proxy when I first tried, may be that's the problem... but I managed to install other plugins previously.

Thanks for your help, I will try to figure this out

**Comment by RobertZenz** [comment]
If you find a possible source of the issue, please report back.

The proxy *might* be a possible source, depending on what it does (for example caching), but I'm not sure.

**Comment by pbi-qfs** [comment]
This  [old comment](https://bugs.eclipse.org/bugs/show_bug.cgi?id=298515#c3) on a comparable issue suggest, that it might have nothing to do with a missing `content.xml` file, but rather really be some network config problem which produces a confusing error message.

**Comment by jc7447** [comment]
There was a mistake in my eclipse proxy configuration, the installation runs well after I fixed it.

@pbi-qfs that's it, the error message is confusing and hide the root cause of the error.

Thanks for the help :)

**Comment by garyliu1119** [comment]
I tried many time to install. It did not work. I also tried to build from source, now the build also failed.
I put a quest here:
https://stackoverflow.com/questions/51598733/cannot-build-ecd-anymore

Can someone help?
