### ISSUE TITLE
[Question] Does this plugin work with classes transformed with ASM

### ISSUE THREAD

**Issue by Gamebuster19901** [ecd-plugin/ecd#115]
Does this plugin work for classes that have been dynamically altered at classload time via ASM?

I.E. Will eclipse's debugger work if the bytecode at runtime doesn't match any .jar binaries on the classpath? (Because the bytecode has been transformed via [ASM](https://asm.ow2.io/), [mixin](https://github.com/SpongePowered/Mixin), etc.)

**Comment by jpstotz** [comment]
ECD and the included decompiles use classes from file-system. There is no connection to a running Java process or Eclipse debugger.
