### ISSUE TITLE
Will this work with Eclipse 4.7.1, because "Eclipse-Class-Decompiler" does not

### ISSUE THREAD

**Issue by davidmichaelkarr** [ecd-plugin/ecd#12]
First, I'll apologize first for filing an issue for something that I don't know will be a problem.  However, I've been using for quite a while the original "Eclipse-Class-Decompiler" that this was was forked from, and when I upgraded my Eclipse to 4.7.1, the decompiler stopped working entirely.  I filed https://github.com/cnfree/Eclipse-Class-Decompiler/issues/36 for this issue.  To get this functionality back, I had to back off to Eclipse 4.7.0.  Before I try to upgrade to 4.7.1 again, and replace the old decompiler with this fork, have you determined that this plugin does NOT have the same problem that the old one did?

**Comment by RobertZenz** [comment]
If I remember correctly, @pbi-qfs stumbled upon this during our tests and fixed it. It is related to the Java 9 Oxygen Beta plugin, which has changed some internal methods. So, yes, this should not happen with EnhancedCD.

But I'd be very grateful if you'd verify that when you find the time.

**Comment by davidmichaelkarr** [comment]
Ok, good.  I just verified that it does not have the same problem (as I have no actual patience, I did this before I saw your reply. :) ).

**Comment by RobertZenz** [comment]
Thanks for testing. :)
