### ISSUE TITLE
Visiting nested classes just shows the top-level class

### ISSUE THREAD

**Issue by davidmichaelkarr** [ecd-plugin/ecd#13]
We use an binary artifact in our builds where a bunch of classes have nested classes (public static) that are referenced from within the top-level class.

In the old Eclipse-Class-Decompiler, if I try to visit one of the nested classes, it brings up the correct class file for the nested class.

In the new ECD, which I just installed today, I'm finding that visiting the nested class just shows the top-level class.  I had to use jd-gui from an archive browser to see the decompilation of the nested classes.

**Comment by RobertZenz** [comment]
Partial repro here, this seems to be a limitation of the FernFlower decompiler, which is set as the default. Can you please set a different default decompiler (like JD or Procyon) in the preferences and try again? Don't forget to close any already opened (decompiled) classes.

**Comment by davidmichaelkarr** [comment]
Oh, duh. I was sort of thinking later "wonder if there's something in the decompiler preferences", but it never resulted in action. :) I verified that switching to jd-core fixed that problem.
