### ISSUE TITLE
Consideration to apply a different code formatting.

### ISSUE THREAD

**Issue by RobertZenz** [ecd-plugin/ecd#19]
We could apply a "Java default" formatting to the source code to make it easier to read and for other people to jump into it. Additionally we can set a save action on the projects which applies the formatter automatically whenever the file is saves, making sure that the code is always well formatted...or at least consistently formatted.

If we settle on this, we should export the settings of the formatter and attach them to the project.

**Comment by jpstotz** [comment]
Applied built-in Eclipse code style to all projects and Java files
