### ISSUE TITLE
ECD plugin installation on eclipse mars failed

### ISSUE THREAD

**Issue by robseidel** [ecd-plugin/ecd#20]
The installation via marketplace lead to an error:
Unable to read repository at https://ecd-plugin.github.io/update/context.xml.
If I look directly for the url, I'll get a 404 http error.
I've also tried to use the mechanism with the update site, but it also needs the context.xml.
As last thing, I've copied the jar files to the plugin folder and restarted eclipse. This lead to errors "Unable to acquire PluginConverter service during generation for ...". I've installed the Eclipse 2.0 Style Plugin Support, but it doesn't show up in the preferences or installation details. 

Is there any way to install this plugin to Eclipse Mars 4.5.2?

**Comment by RobertZenz** [comment]
This should be a duplicate of #11. Please check your Eclipse proxy configuration.

**Comment by robseidel** [comment]
Yes, you are right. I've tested outside of the company network and everything works fine.
