### ISSUE TITLE
Adding jar or zip version of the plugin

### ISSUE THREAD

**Issue by vishnuramana** [ecd-plugin/ecd#27]
Will it be possible to add the plugin as a zip/jar ? I'm behind a proxy which disallows accessing Eclipse Marketplace. So it would be nice to find a zip/jar version available so that people can just download that and install it manually in Eclipse.

**Comment by RobertZenz** [comment]
You're right, we don't have a zip of the current release up, we should change that.

Unfortunately I'm out for the weekend, but I will package the current 3.0 next week and upload it on GitHub.

**Comment by jensduv** [comment]
Any update on the zip for recent version? I am having issues with 2.1 which are resolved in 3.0 but as V1cHu stated behind proxy there are troubles accessing the marketplace.

**Comment by RobertZenz** [comment]
Sorry, that slipped through the cracks because I was quite occupied this week. I've packaged everything [in the releases](https://github.com/ecd-plugin/ecd/releases/tag/v3.0.0.201709092115), you should be able to install the plugin with this.
