### ISSUE TITLE
Missing project org.sf.feeling.decompiler.updatesite

### ISSUE THREAD

**Issue by toesterdahl** [ecd-plugin/ecd#33]
The README refer to the project 'org.sf.feeling.decompiler.updatesite', but it seem to be missing. The root pom refer to the module '../update/', but this directory is also missing.

**Comment by RobertZenz** [comment]
The update site has been moved to [ecd-plugin/update](https://github.com/ecd-plugin/update), I guess the README needs to be updated.

**Comment by pierreonthenet** [comment]
I have exactly the same problem with a fresh install of Eclipse Mars 2 64bit (Version: Mars.2 Release (4.5.2) Build id: 20160218-0600).
I don't have access to https://ecd-plugin.github.io/update/content.xml nor https://github.com/ecd-plugin/update/content.xml, and this is NOT a proxy problem.
Does anyone can access this ?
