### ISSUE TITLE
Project 'org.sf.feeling.decompiler.source.attach' is missing required library: 'lib/maven-scm-provider-jgit-1.9.4.jar'

### ISSUE THREAD

**Issue by zaza** [ecd-plugin/ecd#36]
I get the following error after cloning the repo and importing all the projects into Eclipse:

`Project 'org.sf.feeling.decompiler.source.attach' is missing required library: 'lib/maven-scm-provider-jgit-1.9.4.jar'`

Clearly the jar is missing. I don't see it in the lib folder.

**Comment by RobertZenz** [comment]
Thanks for the notification, I've added the missing jar.
