### ISSUE TITLE
org.sf.feeling.decompiler doesn't compile in Eclipse Oxygen

### ISSUE THREAD

**Issue by zaza** [ecd-plugin/ecd#37]
org.eclipse.jdt.internal.core.SourceMapper has changed its API between org.eclipse.jdt.core 3.12.x (Neon) and 3.13.x (Oxygen) as it works fine for me in the former but fails when trying to compile in Oxygen.

Adding a max version on that dependency should do the trick for now. At least it would be clear why it doesn't compile.

**Comment by RobertZenz** [comment]
I've replaced the method reference with a reflective call. That should make it possible to build it on all versions.

**Comment by zaza** [comment]
Hi Robert, thanks for the quick fix but it doesn't work for me, still get compile errors around `org.sf.feeling.decompiler.editor.ImportSourceMapper.mapSource(IType, char[], IBinaryType,IJavaElement)`. The error says that the Override annotation must be removed as it doesn't match the supertype method.

Have you tried opening and compiling the project in Eclipse Oxygen or with JDT 3.13 (assuming it can be upgraded separately)?

**Comment by RobertZenz** [comment]
I've done the last changes, the plugin can now be compiled against Eclipse Photon.
