### ISSUE TITLE
Is still support chinese text?

### ISSUE THREAD

**Issue by abc45628** [ecd-plugin/ecd#47]
when i using v3.0.0.201709092115, ecd-plugin can show chinese text inWindow > Preferences > Java > Decompiler and right-click context menu
but i update the plugin to v3.1 , chinese text not show, and it show english ,
anything can i do?
img link https://pan.baidu.com/s/1BxabhkgVP7p1acXTHEQbFQ

I see the chinese translation text in v3.0
- org.sf.feeling.decompiler/plugin_zh_CN.properties
- org.sf.feeling.decompiler/plugin_zh_HK.properties
- org.sf.feeling.decompiler/plugin_zh_TW.properties
- org.sf.feeling.decompiler/src/org/sf/feeling/decompiler/i18n/messages_zh_CN.properties
- org.sf.feeling.decompiler/src/org/sf/feeling/decompiler/i18n/messages_zh_HK.properties
- org.sf.feeling.decompiler/src/org/sf/feeling/decompiler/i18n/messages_zh_TW.properties

but those file not in v3.1

**Comment by RobertZenz** [comment]
Yes, we've dropped the Asian translations for the simple reason that we don't have the possibility to maintain, update or even verify them.

**Comment by abc45628** [comment]
When plugin had a major version update ,I can provide the chinese text in a week . 
If so, can you still provide the chinese again?

**Comment by pbi-qfs** [comment]
I see the problem that we (the main maintainer) cannot verify the content. Since the predecessor of this add-on had major trust problems, we currently prefer to provide it in the current fashion.

**Comment by abc45628** [comment]
I got the point , thanks for your answer
