### ISSUE TITLE
Manual installation for those who has corporate proxy

### ISSUE THREAD

**Issue by filipemanuelofs** [ecd-plugin/ecd#48]
Is there some manual explaining for those who has corporate proxy and can't install via Eclipse Marketplace?

**Comment by RobertZenz** [comment]
Yes, you can grab the ZIP package from the [release page](https://github.com/ecd-plugin/ecd/releases) and use that for a manual installation.

**Comment by filipemanuelofs** [comment]
It works, thanks.
