### ISSUE TITLE
什么时候开发idea插件

### ISSUE THREAD

**Issue by linkoog** [ecd-plugin/ecd#49]
idea下的反编译插件，没一个可用的 @RobertZenz

**Comment by RobertZenz** [comment]
I don't speak that language...

**Comment by linkoog** [comment]
can  you  bring  it  to  IntelliJ IDEA ?

**Comment by RobertZenz** [comment]
As I don't use IntelliJ IDEA, no.

Also I don't know feasible it is to reuse existing code, because I don't know how much the two platforms differ.
