### ISSUE TITLE
Error during installation

### ISSUE THREAD

**Issue by edmarmunhoz** [ecd-plugin/ecd#54]
Hi,
I am trying to install the plugin on Eclipse Mars and I am getting this error:
Unable to read repository at https://ecd-plugin.github.io/update/content.xml.
sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

Could someone help on it?
Is there any other way to install?

**Comment by RobertZenz** [comment]
Most likely a duplicate of #11.
