### ISSUE TITLE
Doesn't work on Eclipse 2019 09

### ISSUE THREAD

**Issue by jacopotorrini** [ecd-plugin/ecd#66]
Context menu is always disabled.
Menu on menu bar, if enabled, let you choose a decompiler plugin, but the editor opens with an error and nothing is displayed.

**Comment by RobertZenz** [comment]
Please verify that the default editor for class files is set to ECD (see #43).

The toolbar only becomes enabled ones the correct editor is open.

 > ...with an error and nothing is displayed.

A little bit more details would be helpful here.

**Comment by jacopotorrini** [comment]
Thank you for your very fast reply!
I've done what you've suggested but the problem persists.
Here is a screenshot of what happens:
![image](https://user-images.githubusercontent.com/23704991/65863645-ce63cc80-e370-11e9-814b-04a29670003b.png)

Follows the stack trace from log:

[error.log](https://github.com/ecd-plugin/ecd/files/3669723/error.log)

**Comment by helospark** [comment]
Probably same workaround can be used as in #59

**Comment by jacopotorrini** [comment]
Yes. It does work!
Thanks a lot
