### ISSUE TITLE
there is a bug when handling `/* */`

### ISSUE THREAD

**Issue by p1v07** [ecd-plugin/ecd#67]
The code below in ProcyonDecompiler.java exists a bug, when souce code like picture 2.
![image](https://user-images.githubusercontent.com/54148861/67536457-d4e42a80-f709-11e9-947e-f615864ef9b3.png)

![image](https://user-images.githubusercontent.com/54148861/67536563-5a67da80-f70a-11e9-9d79-de8b3c229b06.png)

**Comment by p1v07** [comment]
Also exist in CfrDecompiler.java, FernFlowerDecompiler.java, JDCoreDecompiler.java

**Comment by jpstotz** [comment]
Has anybody understood for what purpose the decompiler plugins are trying to detect and remove comments? 

https://github.com/ecd-plugin/ecd/blob/65c101f80b811420e4b8042d9364014cc7fcb428/org.sf.feeling.decompiler.procyon/src/org/sf/feeling/decompiler/procyon/decompiler/ProcyonDecompiler.java#L145-L159

Looking at the code I am still missing the understanding why someone would remove all the comments.

**Comment by nbauma109** [comment]
Some decompilers generate very large block comments and provide no option to avoid generating them. They're removed by the plugin because they are an obstacle to realign code for debugging. Regex is not the right tool to identify them and remove them. A proper AST should be used such as Eclipse's one which is already extensively used in this project.

**Comment by jpstotz** [comment]
For a test I have disabled those regex comment removers and it seems only JD-Core and Procyon generate a comment block on each line containing the line number like `/* 105 */`.  For Proxyon there is an option to enable/disable those comments. And for JD-Core there isn't such a "regex comment remover" code. 

Therefore I think it would be best to remove those "regex comment removers". 

@nbauma109 Regarding using AST, that sounds like a good idea. I don't have much experience with the Eclipse AST. Therefore I would be happy if you could provide a PR.

**Comment by nbauma109** [comment]
The line number comments must not be disabled as they're used to realign the code for debugging.
JD-Core has built-in line number realignment, so it does not generate any block comments describing decompiler behaviour, it only generates block comments for line numbers, so there's no comment to remove.

**Comment by jpstotz** [comment]
Fixed via #110
