### ISSUE TITLE
Update the version of jd-core from 0.7.1 to 1.1.1 (Latest)

### ISSUE THREAD

**Issue by grantsheer** [ecd-plugin/ecd#68]
Hi There

Thanks so much for this really useful Eclipse plugin. I was wondering if there was any chance of updating the plugin with the latest release of JD Core 1.1.1?

[JD Core latest release](https://github.com/java-decompiler/jd-core/releases)

Thanks so much,

Grant

**Comment by RobertZenz** [comment]
Sure, as soon as somebody finds the time and thought to do it...I'm a little bit, uh, occupied right now, though. Now that you remind me, the license stuff also needs to be figured out and updated for the next release.

I have added this to the 3.2 milestone, but I'm very open to have this happen in smallish 3.1.1 or some such.

**Comment by grantsheer** [comment]
Hi Robert

Thanks so much for getting back to me so soon. :-)

Hey that'd be great. Is it likely to happen by the beginning of next year?

If its gonna be a while, and you don't mind and its not too difficult to get up to speed with eclipse plugin dev, I'd be happy to supply a patch. Let me know if you open to that.

All the best,

Grant

**Comment by RobertZenz** [comment]
> ...I'd be happy to supply a patch. Let me know if you open to that.

Always!

 > ...its not too difficult to get up to speed with eclipse plugin dev...

Uh, you require an Eclipse installation with the PDE (Plugin Development Environment) and Maven, beyond that the project should work as is. I'm not that familiar with the plugins (@pbi-qfs was doing all the work there), but as far as I can remember it was mostly swapping out the dependencies and fix what breaks.

I currently don't have the project (architecture etc.) on my mental stack anymore, but it should be rather straight forward. #41 might be a good reference.

**Comment by jpstotz** [comment]
I prepared a pull request that included jd-core 1.1.3. see #72

**Comment by jpstotz** [comment]
#72 has been merged.  jd-core 1.1.3 will be included in the next release.
