### ISSUE TITLE
[critical bug] ECD doesn't work with debugger in Eclipse 2019-12 (4.14)

### ISSUE THREAD

**Issue by gayanper** [ecd-plugin/ecd#70]
When trying to debug a class which doesn't have source code, in eclipse 4.14 the ECD doesn't open the decompiled class and show the execution point of the debugging program. It seems to be the way new eclipse version trying to lookup source code which end up in showing a dummy editor with some information on how to attach source code.

**Comment by RobertZenz** [comment]
You sure this isn't another manifestation of #43?

**Comment by gayanper** [comment]
Yes, because everything works if i just try to open the type from Open Type or Ctrl + Click. This only happens when debugging where you try to step into a class which doesn't have source code.

**Comment by RobertZenz** [comment]
Mh, can you give #58 another look, might be relevant.

**Comment by gayanper** [comment]
Yes i think its the same issue. I will close this
