### ISSUE TITLE
Update cfr lib to 0.15.1

### ISSUE THREAD

**Issue by NULL0B** [ecd-plugin/ecd#75]
Hello would be possible to update cfr lib to latest version?

**Comment by jpstotz** [comment]
It seems like cfr has made some changes in it's API, simply updating the JAR file is not enough in this case. 

This will require adaptions to the code used in ECD. I will check how much code have to be changed for being able to use cfr 0.15.1.

**Comment by jpstotz** [comment]
CFR has been updated in c68f17f1020d754e3b2acf3949ecb1f89910509e.

The updated code seems to work, however I have to do some more tests to verify that.

**Comment by pbi-qfs** [comment]
@jpstotz Thanks for the update!
