### ISSUE TITLE
Unable to read repository at https://ecd-plugin.github.io/update/content.xml

### ISSUE THREAD

**Issue by angusdev** [ecd-plugin/ecd#80]
Eclipse Version:
Version: 2021-03 (4.19.0)
Build id: 20210312-0638

Show below error message when Install in marketplace or "Install New Software..."
Unable to read repository at https://ecd-plugin.github.io/update/content.xml

**Comment by RobertZenz** [comment]
Should be a duplicate of #11, something wrong with your (Eclipse) proxy configuration.

**Comment by angusdev** [comment]
Yes this is my proxy problem.
