### ISSUE TITLE
Warning on "unsigned software" when installing on Eclipse 2021-06 (4.20.0)

### ISSUE THREAD

**Issue by cyberravn** [ecd-plugin/ecd#81]
I got this warning on installing unsigned software when installing this on Eclipse 2021-06 (4.20.0). Looks a bit disconcerting so I thought I will ask here if that warning is expected?

**Comment by jpstotz** [comment]
Yeas, ECD is currently not signed. The correct way would be to sign all the generated JAR files using a trusted code signing certificate. But I am not sure how to get such a code signing certificate for an open source project. Usually for getting a code signing certificate you have to pay a lot of money per year to a commercial CA.

May be for signing Eclipse plugins there is an easier way, if somebody has knowledge or experience on this topic feel free to use this issue to teach us the details.

**Comment by jpstotz** [comment]
Next ECD 3.3.0 release will be signed using a self-signed certificate.
