### ISSUE TITLE
Add Quiltflower

### ISSUE THREAD

**Issue by tr7zw** [ecd-plugin/ecd#85]
"Quiltflower is a fork of Fernflower aiming to create code that is as accurate and clean as possible."

Github: https://github.com/QuiltMC/quiltflower
Reddit post: https://old.reddit.com/r/java/comments/ue8u59/new_open_source_java_decompiler/

**Comment by jpstotz** [comment]
Quiltflower 1.9 has been added as new optional decompiler feature in 0bdb0a6d539d1df1b59e0f129694d85634627b71

**Comment by jpstotz** [comment]
Quiltflower is included in ECD 3.3.0.

**Comment by tr7zw** [comment]
Really cool. Thanks 👍
