### ISSUE TITLE
please Update  JD-Core to the newest 1.6.6 version

### ISSUE THREAD

**Issue by hheehhaa** [ecd-plugin/ecd#95]
Dear authors, the JD-Core has updated to version 1.6.6, please upgrade the JD-Core of ECD to the newset version, whose current verison is 1.1.3. Greate Thanks!

**Comment by jpstotz** [comment]
In [JD-Core Github project ](https://github.com/java-decompiler/jd-core/releases) and in [maven repository](https://mvnrepository.com/artifact/org.jd/jd-core) the latest version is 1.1.3. 

What JD-core project are you talking about?

**Comment by jpstotz** [comment]
Most likely you were mistaken JD-GUI with JD-core. The latest JD-GUI version is 1.6.6 but latest JD-Core version is 1.1.3.
