### ISSUE TITLE
Unable to configure Enhanced Class Decompiler in Eclipse 2023-06 having JDK17 installed in a 64 bit Windows 11 system

### ISSUE THREAD

**Issue by pforpramit** [ecd-plugin/ecd#96]
I am trying to configure Java Decompiler in Eclipse 2023-06 in order to get into .class files from within JARs, where no sources are attached. For that, I have installed the Enhanced Class Decompiler 3.3.0 plugin from Eclipse Marketplace -

![image](https://github.com/ecd-plugin/ecd/assets/112875951/fc2777e4-f5d4-4bfd-a46d-c6d090412efc)

Following that I have restarted, quit and opened Eclipse multiple times. However, I don't see any new editor to be added under Associated Editors in this path, Windows -> Preference -> Editors -> File Associations. The available options don't work.

![image](https://github.com/ecd-plugin/ecd/assets/112875951/ab7baabd-ad5f-499e-b42f-cecd7aa1dab3)

Also, I have tried searching Decompiler under Preference search, which, in usual case, is supposed to be there under Java. But here in my case, nothing shows up -

![image](https://github.com/ecd-plugin/ecd/assets/112875951/cec7c24c-d4c2-4499-b000-516a1c991e42)

Additionally, I installed it again both from the project page guided steps (https://ecd-plugin.github.io/ecd/) and directly doing a drag and drop of the installer in running Eclipse workspace. However, still no luck. Also, once installed they do show up in that software list (Help > About Eclipse > Installation Details > Installation Software) though.

Just wanted to mention here, since I am working in the Eclipse 2023-06 edition installed in a 64 bit Windows 11 system with JDK 17, could this combination have anything to do with this issue?

**Comment by jpstotz** [comment]
Please make sure ECD is correctly installed. Go to Help menu -> About Eclipse IDE -> Installation Details and search for `decompile`. You should get this result:
![image](https://github.com/ecd-plugin/ecd/assets/924885/6ea57edb-dc6a-41c4-b6a7-2998bc4972b9)

**Comment by pforpramit** [comment]
Yes! As I mentioned, they do show up there every time in whichever way I install.

**Comment by jpstotz** [comment]
Then please select a class file in Eclipse and the it's context menu. You should see a menu entry `Open Class With` and in it the available decompilers. 

Not sure why ECD does not show-up in preferences. You can check Eclipse log file for ECD or `decompiler` related errors, you can find it in your workspace directory `.metadata/.log`.

**Comment by pforpramit** [comment]
Above option itself is not available in my case. I tried installing Eclipse 2023-03 and there this entire Decompiler plugin thing has worked in one shot! Looks like this is really an issue currently with the latest version i.e., Eclipse 2023-06 or at least for the combination that I had, Windows 11 64 Bit + JDK17 + Eclipse 2023-96, not sure!

**Comment by hugithordarson** [comment]
FWIW I'm having the same problem with 2023-06 runnin on an M1 Mac.

**Comment by jpstotz** [comment]
I have multiple installations with Eclipse 2023-06 (some updated from older versions and some installed from scratch) and ECD running without any problems (usually I use the Eclipse RCP version). 
All running with Java 17 (externally installed JDK 17 from https://adoptium.net).

Therefore I need your help to identify the problem. Please check [Eclipse log](https://github.com/ecd-plugin/ecd/issues/96#issuecomment-1674304370) for ECD related errors and post them here.

**Comment by jpstotz** [comment]
I just set-up a VM with Windows 11 and downloaded Eclipse Eclipse IDE 2023-06 R - Eclipse IDE for Java Developers
, started it (Eclipse contains integrated JDk17, so no external JDK is necessary), opened Eclipse Marketplace, installed ecd, Eclipse restart and File Associations viewer shows me two entries as it should be: 

![image](https://github.com/ecd-plugin/ecd/assets/924885/5025609a-fefe-4bd4-b48c-59310160859d)

@pforpramit  @hugithordarson Please provide more details about your Eclipse installations and the used JDK.

**Comment by hugithordarson** [comment]
@jpstotz  You mentioning running JDK 17 did the trick.  My Eclipse installation was running on JDK 19, so I tried another clean install with Eclipse configured to run under JDK 17, and lo and behold, ECD works fine.

However, what is even weirder is that if I now re-configure Eclipse to run under JDK 19 (by just editing `eclipse.ini`), the decompiler still works fine! So it looks like it's just the installation process that somehow got bodged on JDK 19. Which seems… Odd.

Unfortunately I do not see anything interesting in Eclipse's log file at a glance. But with this workaround, I'm good :).

Thanks for looking into this, and for the awesome software!
