### ISSUE TITLE
[Question] Is it possible to integrate this plugin into a text editor ?

### ISSUE THREAD

**Issue by PerilousBooklet** [ecd-plugin/ecd#97]
I was wondering if this plugin only works with Eclipse Java Edition or if it can be interfaced with another text editor by way of a dedicated plugin (es. Lite XL text editor, a dedicated lua plugin).

**Comment by jpstotz** [comment]
ECD is an Eclipse plugin, therefore only Eclipse is supported. As the plugin code is open source feel free to adapt it to other Java based programs.
